language: python

matrix:
    include:
        - os: linux
          python: 2.7

        - os: linux
          python: 3.5

install:
    - pip install --upgrade pip
    # via https://github.com/angr/angr/issues/52
    - pip install -I --no-binary capstone
    - pip install --upgrade pep8 pytest-cov pytest flake8
    - pip install -e .
    # capstone puts the .so in the wrong directory when installed via pip
    # ref: https://github.com/aquynh/capstone/issues/445
    #- cp -f /home/travis/virtualenv/python3.5.4/lib/python3.5/site-packages/env/lib/python3.5/site-packages/capstone/libcapstone.so /home/travis/virtualenv/python3.5.4/lib/python3.5/site-packages/capstone
    #- cp -f /home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/env/lib/python2.7/site-packages/capstone/libcapstone.so /home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/capstone
    - find /home/travis/virtualenv/ -name '*libcapstone.so'
    - find /home/travis/virtualenv/ -name '*libcapstone.so' | while read -r LINE; do mv ${LINE} /home/travis/virtualenv/*/lib/*/site-packages/capstone; done


before_script:
    # stop the build if there are Python syntax errors or undefined names
    - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
    # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

script:
    - find . -name \*.py -exec pep8 --ignore=E501 {} \;
    - py.test ./tests/ -v --cov=idb
